"use strict";

/* Central product catalog: add products here and every page updates automatically. */
const PRODUCTS = [
  {id:"nova-phone",name:"Nova Pro Smartphone",category:"Mobile",price:999,oldPrice:1099,rating:4.8,reviews:318,badge:"Bestseller",image:"assets/smartphone-pro.avif",stock:14,description:"A precision-built smartphone with a vivid edge-to-edge display, pro-grade camera system and all-day battery.",features:["6.7-inch OLED display","48 MP camera system","All-day battery","256 GB storage"]},
  {id:"aero-laptop",name:"AeroBook Air",category:"Computing",price:1099,rating:4.7,reviews:184,badge:"New",image:"assets/laptop-air.jpg",stock:9,description:"An exceptionally portable laptop for focused work, creative projects and life on the move.",features:["13-inch high-resolution display","18-hour battery","16 GB unified memory","Silent fanless design"]},
  {id:"studio-laptop",name:"StudioBook Pro",category:"Computing",price:2199,rating:4.9,reviews:126,badge:"Pro pick",image:"assets/laptop-pro.jpg",stock:6,description:"Desktop-class performance in a refined notebook built for demanding creative and technical work.",features:["16-inch XDR display","32 GB unified memory","1 TB fast storage","Pro performance processor"]},
  {id:"halo-headphones",name:"Halo ANC Headphones",category:"Audio",price:349,oldPrice:399,rating:4.9,reviews:521,badge:"Top rated",image:"assets/headphones.webp",stock:22,description:"Immersive over-ear headphones with adaptive noise cancellation and carefully balanced spatial sound.",features:["Adaptive noise cancellation","40-hour listening","Spatial audio","Memory foam cushions"]},
  {id:"air-buds",name:"Air Wireless Buds",category:"Audio",price:189,rating:4.7,reviews:802,badge:"Popular",image:"assets/airpods.jpg",stock:30,description:"Compact true wireless earbuds with effortless pairing, rich sound and a pocket-sized charging case.",features:["Active noise cancellation","30-hour total battery","Wireless charging case","Sweat resistant"]},
  {id:"core-earpods",name:"Core Wired EarPods",category:"Audio",price:29,rating:4.4,reviews:1102,badge:"Essential",image:"assets/earpods.jpg",stock:44,description:"Dependable everyday earphones with clear calls, balanced sound and an integrated remote.",features:["Crisp balanced sound","Built-in microphone","Inline controls","Comfort fit"]},
  {id:"pulse-watch",name:"Pulse Smart Watch",category:"Wearables",price:279,oldPrice:319,rating:4.6,reviews:245,badge:"Save 13%",image:"assets/smartwatch.jpg",stock:17,description:"A streamlined health and activity companion that keeps important information close at hand.",features:["Heart-rate tracking","Sleep insights","GPS workouts","5-day battery"]},
  {id:"power-max",name:"PowerMax 20K",category:"Accessories",price:79,rating:4.8,reviews:433,badge:"Travel pick",image:"assets/powerbank-max.jpg",stock:27,description:"High-capacity fast charging for phones, tablets and lightweight laptops wherever the day takes you.",features:["20,000 mAh capacity","65 W USB-C charging","Three-device output","Digital power display"]},
  {id:"power-mini",name:"PowerMini 10K",category:"Accessories",price:49,rating:4.5,reviews:367,badge:"Compact",image:"assets/powerbank-compact.jpg",stock:35,description:"Pocket-friendly backup power with quick charging and a durable, understated shell.",features:["10,000 mAh capacity","20 W fast charging","Dual USB output","Flight safe"]},
  {id:"essential-tee",name:"Essential Cotton Tee",category:"Apparel",price:39,rating:4.6,reviews:196,badge:"Organic",image:"assets/premium-tshirt.avif",stock:52,description:"A clean everyday T-shirt made from soft, breathable organic cotton in a relaxed modern cut.",features:["100% organic cotton","Pre-washed softness","Relaxed unisex fit","Responsibly made"]},
  {id:"everyday-shirt",name:"Everyday Oxford Shirt",category:"Apparel",price:69,rating:4.5,reviews:88,badge:"Classic",image:"assets/casual-shirt.jpg",stock:28,description:"A versatile cotton Oxford with a refined silhouette that moves easily from work to weekends.",features:["Premium cotton Oxford","Easy-care finish","Modern regular fit","Reinforced seams"]},
  {id:"capsule-set",name:"Modern Capsule Set",category:"Apparel",price:129,oldPrice:159,rating:4.7,reviews:74,badge:"Limited",image:"assets/clothing-collection.jpg",stock:11,description:"A coordinated set of versatile staples designed to make everyday dressing effortless.",features:["Three coordinated pieces","Soft breathable fabric","Mix-and-match palette","Inclusive sizing"]}
];

const $ = (selector, root=document) => root.querySelector(selector);
const $$ = (selector, root=document) => [...root.querySelectorAll(selector)];
const money = value => new Intl.NumberFormat("en-US",{style:"currency",currency:"USD"}).format(value);
const storage = {
  get(key,fallback){try{return JSON.parse(localStorage.getItem(key)) ?? fallback}catch{return fallback}},
  set(key,value){try{localStorage.setItem(key,JSON.stringify(value))}catch{toast("Your browser blocked local storage.")}}
};
let cart = storage.get("nexora-cart",[]).filter(item=>PRODUCTS.some(p=>p.id===item.id)&&Number.isInteger(item.quantity)&&item.quantity>0);

function escapeHTML(value){return String(value).replace(/[&<>'"]/g,char=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[char]))}
function productById(id){return PRODUCTS.find(product=>product.id===id)}
function imageFallback(event){event.currentTarget.src="data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='800' height='800'%3E%3Crect width='100%25' height='100%25' fill='%23e8eadf'/%3E%3Ctext x='50%25' y='50%25' text-anchor='middle' fill='%23696b63' font-family='Arial' font-size='28'%3ENexora%3C/text%3E%3C/svg%3E"}
function saveCart(){storage.set("nexora-cart",cart);updateCartCount()}
function updateCartCount(){const count=cart.reduce((sum,item)=>sum+item.quantity,0);$$('.cart-count').forEach(el=>{el.textContent=count;el.hidden=count===0})}
function addToCart(id,quantity=1){const product=productById(id);if(!product||product.stock<1)return toast("This product is unavailable.");const existing=cart.find(item=>item.id===id);const next=Math.min((existing?.quantity||0)+quantity,product.stock);if(existing)existing.quantity=next;else cart.push({id,quantity:Math.min(quantity,product.stock)});saveCart();toast(`${product.name} added to cart.`)}
function removeFromCart(id){const product=productById(id);cart=cart.filter(item=>item.id!==id);saveCart();toast(`${product?.name||"Item"} removed.`);if(document.body.dataset.page==="cart")renderCart()}
function updateQuantity(id,quantity){const product=productById(id);if(!product)return;quantity=Math.max(1,Math.min(Number(quantity)||1,product.stock));const item=cart.find(entry=>entry.id===id);if(item)item.quantity=quantity;saveCart();if(document.body.dataset.page==="cart")renderCart()}
function totals(){const subtotal=cart.reduce((sum,item)=>sum+(productById(item.id)?.price||0)*item.quantity,0);const shipping=subtotal===0||subtotal>=75?0:8.95;const tax=subtotal*.08;return{subtotal,shipping,tax,total:subtotal+shipping+tax}}
function toast(message){const root=$("#toast-root")||document.body;const el=document.createElement("div");el.className="toast";el.textContent=message;root.append(el);setTimeout(()=>el.remove(),3100)}

function renderChrome(){
  const page=document.body.dataset.page;
  $("#site-header").innerHTML=`<header class="site-header"><nav class="nav" aria-label="Primary"><a class="brand" href="index.html" aria-label="Nexora home">Nexora<i></i></a><div class="nav-links" id="nav-links"><a class="${page==='home'?'active':''}" href="index.html">Home</a><a class="${['products','product'].includes(page)?'active':''}" href="products.html">Shop</a><a class="${page==='about'?'active':''}" href="about.html">About</a><a class="${page==='contact'?'active':''}" href="contact.html">Contact</a></div><div class="nav-actions"><button class="icon-button" id="search-toggle" aria-label="Search" aria-expanded="false">⌕</button><button class="icon-button" id="theme-toggle" aria-label="Toggle color theme">◐</button><a class="icon-button account-link" href="login.html" aria-label="Account">♙</a><a class="icon-button cart-link" href="cart.html" aria-label="Cart">◌<span class="cart-count"></span></a><button class="icon-button hamburger" id="menu-toggle" aria-label="Open menu" aria-expanded="false">☰</button></div></nav><div class="search-panel" id="search-panel" hidden><div class="search-wrap"><span>⌕</span><label class="sr-only" for="global-search">Search products</label><input id="global-search" type="search" placeholder="Search products and categories…" autocomplete="off"><button class="icon-button" id="search-close" aria-label="Close search">×</button></div><div class="suggestions" id="search-suggestions"></div></div></header>`;
  $("#site-footer").innerHTML=`<footer class="site-footer"><div class="footer-inner"><div class="footer-top"><div><a class="brand" href="index.html">Nexora<i></i></a><p>Thoughtfully selected essentials for modern life.</p></div><div><h4>Shop</h4><div class="footer-links"><a href="products.html">All products</a><a href="products.html?category=Audio">Audio</a><a href="products.html?category=Computing">Computing</a><a href="products.html?category=Apparel">Apparel</a></div></div><div><h4>Company</h4><div class="footer-links"><a href="about.html">About</a><a href="contact.html">Contact</a><a href="login.html">Account</a></div></div><div><h4>Help</h4><div class="footer-links"><a href="contact.html">Shipping</a><a href="contact.html">Returns</a><a href="contact.html">Privacy</a></div></div></div><div class="footer-bottom"><span>© ${new Date().getFullYear()} Nexora. Demo storefront.</span><span>Secure by design · Accessible · Responsive</span></div></div></footer>`;
  const savedTheme=storage.get("nexora-theme",matchMedia("(prefers-color-scheme: dark)").matches?"dark":"light");document.documentElement.dataset.theme=savedTheme;
  $("#theme-toggle").addEventListener("click",()=>{const next=document.documentElement.dataset.theme==="dark"?"light":"dark";document.documentElement.dataset.theme=next;storage.set("nexora-theme",next)});
  $("#menu-toggle").addEventListener("click",event=>{const open=$("#nav-links").classList.toggle("open");document.body.classList.toggle("menu-open",open);event.currentTarget.setAttribute("aria-expanded",open)});
  const toggleSearch=open=>{$("#search-panel").hidden=!open;$("#search-toggle").setAttribute("aria-expanded",open);if(open)setTimeout(()=>$("#global-search").focus(),0)};
  $("#search-toggle").addEventListener("click",()=>toggleSearch($("#search-panel").hidden));$("#search-close").addEventListener("click",()=>toggleSearch(false));
  $("#global-search").addEventListener("input",renderSuggestions);$("#global-search").addEventListener("keydown",event=>{if(event.key==="Enter"&&event.currentTarget.value.trim())location.href=`products.html?q=${encodeURIComponent(event.currentTarget.value.trim())}`;if(event.key==="Escape")toggleSearch(false)});
  addEventListener("scroll",()=>$(".site-header")?.classList.toggle("scrolled",scrollY>12),{passive:true});updateCartCount();
}
function renderSuggestions(event){const term=event.currentTarget.value.trim().toLowerCase();const root=$("#search-suggestions");if(!term){root.innerHTML="";return}const matches=PRODUCTS.filter(p=>`${p.name} ${p.category} ${p.description}`.toLowerCase().includes(term)).slice(0,5);root.innerHTML=matches.length?matches.map(p=>`<a class="suggestion" href="product.html?id=${p.id}"><img src="${p.image}" alt=""><span><strong>${escapeHTML(p.name)}</strong><small>${p.category}</small></span><b>${money(p.price)}</b></a>`).join(""):`<a class="suggestion" href="products.html?q=${encodeURIComponent(term)}"><span>Search all products for “${escapeHTML(term)}”</span></a>`;bindImageFallbacks(root)}
function productCard(product){return `<article class="product-card"><a href="product.html?id=${product.id}" aria-label="View ${escapeHTML(product.name)}"><div class="product-media"><span class="product-badge">${escapeHTML(product.badge)}</span><img src="${product.image}" alt="${escapeHTML(product.name)}" loading="lazy"></div></a><button class="quick-add" data-add="${product.id}" aria-label="Add ${escapeHTML(product.name)} to cart">+</button><div class="product-info"><span class="product-category">${product.category}</span><a href="product.html?id=${product.id}"><h3>${escapeHTML(product.name)}</h3></a><div class="product-meta"><span class="rating" aria-label="${product.rating} out of 5 stars">★ ${product.rating} <small>(${product.reviews})</small></span><span class="price">${money(product.price)}${product.oldPrice?`<span class="old-price">${money(product.oldPrice)}</span>`:""}</span></div></div></article>`}
function bindProductActions(root=document){$$('[data-add]',root).forEach(button=>button.addEventListener("click",()=>addToCart(button.dataset.add)));bindImageFallbacks(root)}
function bindImageFallbacks(root=document){$$("img",root).forEach(img=>img.addEventListener("error",imageFallback,{once:true}))}

function initHome(){const categories=[{name:"Audio",image:"assets/headphones.webp"},{name:"Computing",image:"assets/laptop-pro.jpg"},{name:"Apparel",image:"assets/clothing-collection.jpg"}];$("#category-grid").innerHTML=categories.map(c=>`<a class="category-card" href="products.html?category=${encodeURIComponent(c.name)}"><img src="${c.image}" alt="${c.name} collection"><div><span>Explore</span><h3>${c.name} →</h3></div></a>`).join("");$("#featured-products").innerHTML=PRODUCTS.slice(0,4).map(productCard).join("");bindProductActions();$("#newsletter-form").addEventListener("submit",event=>{event.preventDefault();const input=$("#newsletter-email");if(!input.checkValidity())return input.reportValidity();toast("You’re on the list.");event.currentTarget.reset()})}
function initProducts(){const params=new URLSearchParams(location.search);let state={category:params.get("category")||"All",query:(params.get("q")||"").toLowerCase(),max:2500,stock:false,sort:"featured"};const categories=["All",...new Set(PRODUCTS.map(p=>p.category))];$("#category-filters").innerHTML=categories.map(category=>`<label><input type="radio" name="category" value="${category}" ${state.category===category?'checked':''}> ${category}</label>`).join("");
  function render(){let items=PRODUCTS.filter(p=>(state.category==="All"||p.category===state.category)&&p.price<=state.max&&(!state.stock||p.stock>0)&&(!state.query||`${p.name} ${p.category} ${p.description}`.toLowerCase().includes(state.query)));if(state.sort==="price-asc")items.sort((a,b)=>a.price-b.price);if(state.sort==="price-desc")items.sort((a,b)=>b.price-a.price);if(state.sort==="rating")items.sort((a,b)=>b.rating-a.rating);$("#product-grid").innerHTML=items.map(productCard).join("");$("#result-count").textContent=`${items.length} product${items.length===1?'':'s'}${state.query?` for “${params.get('q')}”`:''}`;$("#empty-products").hidden=items.length>0;bindProductActions($("#product-grid"))}
  function clear(){state={category:"All",query:"",max:2500,stock:false,sort:"featured"};$("input[name=category][value=All]").checked=true;$("#price-filter").value=2500;$("#price-value").textContent="$2,500";$("#stock-filter").checked=false;$("#sort-products").value="featured";history.replaceState(null,"","products.html");render()}
  $$('input[name="category"]').forEach(input=>input.addEventListener("change",()=>{state.category=input.value;render()}));$("#price-filter").addEventListener("input",event=>{state.max=Number(event.target.value);$("#price-value").textContent=money(state.max);render()});$("#stock-filter").addEventListener("change",event=>{state.stock=event.target.checked;render()});$("#sort-products").addEventListener("change",event=>{state.sort=event.target.value;render()});$("#clear-filters").addEventListener("click",clear);$("#empty-clear").addEventListener("click",clear);$("#open-filters").addEventListener("click",()=>$("#filters").classList.add("open"));$("#close-filters").addEventListener("click",()=>$("#filters").classList.remove("open"));render()}
function initProduct(){const id=new URLSearchParams(location.search).get("id");const product=productById(id)||PRODUCTS[0];document.title=`${product.name} | Nexora`;$("#product-crumb").textContent=product.name;$("#product-detail").innerHTML=`<div class="detail-media"><img src="${product.image}" alt="${escapeHTML(product.name)}"></div><div class="detail-copy"><span class="eyebrow">${product.category} · ${product.badge}</span><h1>${escapeHTML(product.name)}</h1><span class="rating">★★★★★ ${product.rating} (${product.reviews} reviews)</span><div class="detail-price">${money(product.price)}${product.oldPrice?`<span class="old-price">${money(product.oldPrice)}</span>`:""}</div><p class="detail-description">${escapeHTML(product.description)}</p><ul class="feature-list">${product.features.map(f=>`<li>✓ ${escapeHTML(f)}</li>`).join("")}</ul><div class="detail-actions"><div class="qty-control"><button type="button" id="detail-minus" aria-label="Decrease quantity">−</button><input id="detail-qty" value="1" inputmode="numeric" aria-label="Quantity"><button type="button" id="detail-plus" aria-label="Increase quantity">+</button></div><button class="button button-accent" id="detail-add">Add to cart</button></div><div class="delivery-note"><strong>In stock.</strong> Free delivery on orders over $75. Easy 30-day returns.</div></div>`;const qty=$("#detail-qty");const clamp=()=>qty.value=Math.max(1,Math.min(Number(qty.value)||1,product.stock));$("#detail-minus").addEventListener("click",()=>{qty.value=Number(qty.value)-1;clamp()});$("#detail-plus").addEventListener("click",()=>{qty.value=Number(qty.value)+1;clamp()});qty.addEventListener("change",clamp);$("#detail-add").addEventListener("click",()=>addToCart(product.id,Number(qty.value)));$("#related-products").innerHTML=PRODUCTS.filter(p=>p.id!==product.id).sort((a,b)=>Number(b.category===product.category)-Number(a.category===product.category)).slice(0,4).map(productCard).join("");bindProductActions();bindImageFallbacks()}
function summaryMarkup(includeItems=false){const value=totals();return `${includeItems?`<h2>Your order</h2><div class="summary-items">${cart.map(item=>{const p=productById(item.id);return `<div class="summary-mini"><img src="${p.image}" alt=""><span>${escapeHTML(p.name)} × ${item.quantity}</span><b>${money(p.price*item.quantity)}</b></div>`}).join("")}</div>`:'<h2>Order summary</h2>'}<div class="summary-row"><span>Subtotal</span><strong>${money(value.subtotal)}</strong></div><div class="summary-row"><span>Shipping</span><strong>${value.shipping?money(value.shipping):"Free"}</strong></div><div class="summary-row"><span>Estimated tax</span><strong>${money(value.tax)}</strong></div><div class="summary-row total"><span>Total</span><strong>${money(value.total)}</strong></div>`}
function renderCart(){const root=$("#cart-content");if(!cart.length){root.className="empty-state";root.innerHTML=`<h2>Your cart is ready for something good.</h2><p>Explore the collection and add a few favorites.</p><a class="button" href="products.html">Start shopping</a>`;return}root.className="cart-layout";root.innerHTML=`<div class="cart-list">${cart.map(item=>{const p=productById(item.id);return `<article class="cart-item"><a href="product.html?id=${p.id}"><img src="${p.image}" alt="${escapeHTML(p.name)}"></a><div><span class="product-category">${p.category}</span><h3><a href="product.html?id=${p.id}">${escapeHTML(p.name)}</a></h3><p>In stock · Ships in 1–2 days</p><div class="cart-item-actions"><div class="qty-control"><button data-qty="${p.id}" data-step="-1" aria-label="Decrease quantity">−</button><input value="${item.quantity}" data-input-qty="${p.id}" aria-label="Quantity for ${escapeHTML(p.name)}"><button data-qty="${p.id}" data-step="1" aria-label="Increase quantity">+</button></div><button class="remove-button" data-remove="${p.id}">Remove</button></div></div><strong>${money(p.price*item.quantity)}</strong></article>`}).join("")}</div><aside class="order-summary">${summaryMarkup()}<a class="button button-accent" href="checkout.html">Secure checkout</a><a class="text-link" href="products.html">← Continue shopping</a></aside>`;$$('[data-remove]',root).forEach(button=>button.addEventListener("click",()=>removeFromCart(button.dataset.remove)));$$('[data-qty]',root).forEach(button=>button.addEventListener("click",()=>{const item=cart.find(i=>i.id===button.dataset.qty);updateQuantity(item.id,item.quantity+Number(button.dataset.step))}));$$('[data-input-qty]',root).forEach(input=>input.addEventListener("change",()=>updateQuantity(input.dataset.inputQty,input.value)));bindImageFallbacks(root)}

function validateForm(form){let valid=true;$$('.field',form).forEach(field=>{const input=$("input,select,textarea",field);if(!input)return;let message="";if(input.validity.valueMissing)message="This field is required.";else if(input.validity.typeMismatch)message="Enter a valid email address.";else if(input.validity.tooShort)message=`Use at least ${input.minLength} characters.`;else if(input.validity.patternMismatch)message="Check the format and try again.";field.classList.toggle("invalid",Boolean(message));const small=$("small",field);if(small)small.textContent=message;if(message)valid=false});return valid}
function passesLuhn(value){
  const digits=value.replace(/\D/g,"");
  if(digits.length<13||digits.length>19)return false;
  let sum=0;let doubleDigit=false;
  for(let index=digits.length-1;index>=0;index--){
    let digit=Number(digits[index]);
    if(doubleDigit&&((digit*=2)>9))digit-=9;
    sum+=digit;doubleDigit=!doubleDigit;
  }
  return sum%10===0;
}
function expiryIsFuture(value){
  const match=/^(0[1-9]|1[0-2])\/(\d{2})$/.exec(value);
  if(!match)return false;
  const expiry=new Date(2000+Number(match[2]),Number(match[1]),1);
  const currentMonth=new Date();currentMonth.setDate(1);currentMonth.setHours(0,0,0,0);
  return expiry>currentMonth;
}
function initCheckout(){
  if(!cart.length){$("#checkout-form").hidden=true;$("#checkout-empty").hidden=false;return}

  $("#checkout-summary").innerHTML=summaryMarkup(true)+`<button id="demo-checkout" class="button button-accent" type="submit">Place demo order · ${money(totals().total)}</button><p class="checkout-status" id="checkout-status" role="status">Debit card is the only payment method.</p>`;
  bindImageFallbacks($("#checkout-summary"));
  const form=$("#checkout-form");
  const cardNumber=form.elements.cardNumber;
  const expiry=form.elements.expiry;
  cardNumber.addEventListener("input",()=>{cardNumber.value=cardNumber.value.replace(/\D/g,"").slice(0,19).replace(/(.{4})/g,"$1 ").trim()});
  expiry.addEventListener("input",()=>{const digits=expiry.value.replace(/\D/g,"").slice(0,4);expiry.value=digits.length>2?`${digits.slice(0,2)}/${digits.slice(2)}`:digits});
  form.addEventListener("input",event=>{const field=event.target.closest(".field");if(field){field.classList.remove("invalid");$("small",field).textContent=""}});
  form.addEventListener("submit",event=>{
    event.preventDefault();
    let valid=validateForm(form);
    if(!passesLuhn(cardNumber.value)){setFieldError(cardNumber,"Enter a valid test card number.");valid=false}
    if(!expiryIsFuture(expiry.value)){setFieldError(expiry,"Enter a future expiry date in MM/YY format.");valid=false}
    if(!valid)return toast("Please check the highlighted checkout fields.");
    const reference=`NX-${Date.now().toString(36).toUpperCase()}-${crypto.getRandomValues(new Uint32Array(1))[0].toString(36).slice(0,5).toUpperCase()}`;
    form.reset();cart=[];saveCart();
    form.hidden=true;$(".page-hero").hidden=true;
    $("#order-reference").textContent=`Demo order reference: ${reference}.`;
    $("#order-success").hidden=false;
    toast("Demo checkout completed. No payment was charged.");
  });
}
function setFieldError(input,message){const field=input.closest(".field");field.classList.add("invalid");$("small",field).textContent=message}
function initForms(){const contact=$("#contact-form");if(contact)contact.addEventListener("submit",event=>{event.preventDefault();if(!validateForm(contact))return toast("Please check the form.");contact.reset();toast("Message received. We’ll be in touch.")});const tabs=$$('[data-auth-tab]');tabs.forEach(tab=>tab.addEventListener("click",()=>{tabs.forEach(t=>t.classList.toggle("active",t===tab));$("#login-form").hidden=tab.dataset.authTab!=="login";$("#signup-form").hidden=tab.dataset.authTab!=="signup"}));const login=$("#login-form");if(login)login.addEventListener("submit",event=>{event.preventDefault();if(!validateForm(login))return;toast("Demo sign-in validated. Connect a backend to authenticate.")});const signup=$("#signup-form");if(signup)signup.addEventListener("submit",event=>{event.preventDefault();let valid=validateForm(signup);if(signup.elements.password.value!==signup.elements.confirmPassword.value){setFieldError(signup.elements.confirmPassword,"Passwords do not match.");valid=false}if(!signup.elements.terms.checked){toast("Accept the terms to continue.");valid=false}if(valid)toast("Demo account form validated. Connect a backend to register.")})}

document.addEventListener("DOMContentLoaded",()=>{renderChrome();bindImageFallbacks();const page=document.body.dataset.page;if(page==="home")initHome();if(page==="products")initProducts();if(page==="product")initProduct();if(page==="cart")renderCart();if(page==="checkout")initCheckout();if(["contact","login"].includes(page))initForms()});
